In [179]:
# !pip install [package name] # use this to install packages in jupyter
# !pip install tensorflow_addons # likely need to run this without the comment
# from geopy.geocoders import Nominatim

import pandas as pd
#from geopy.geocoders import Nominatim
import numpy as np
import re
import matplotlib.pyplot as plt
from matplotlib import style
style.use('seaborn-white')
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import tensorflow as tf 
from tensorflow import keras
import tensorflow_addons.metrics as tfa
from tensorflow_addons.metrics import RSquare

In [197]:
df = pd.read_excel(r"C:\Users\Owner\Documents\UNL\2022 Fall\Math 435\Datasets\CleanedDataV2.xlsx") 
# change data path to wherever the dataset is at

In [198]:
#df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35104 entries, 0 to 35103
Data columns (total 36 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   NBHD          35104 non-null  object        
 1   PID           35104 non-null  object        
 2   Situs         35104 non-null  object        
 3   PrpCls        35104 non-null  object        
 4   PrUse         35104 non-null  int64         
 5   CDU           35104 non-null  int64         
 6   Qual          35104 non-null  int64         
 7   YrRD          35104 non-null  object        
 8   Remd          35104 non-null  object        
 9   Imp           35104 non-null  object        
 10  TLA           35104 non-null  int64         
 11  YrBlt         35104 non-null  int64         
 12  GarCap        35104 non-null  int64         
 13  Bedrm         35103 non-null  float64       
 14  FND           35099 non-null  float64       
 15  801Units      35104 non-null  int64 

In [199]:
useful_df = df[["CDU","Qual","TLA","GarCap","Bedrm","FND","801Units","802Units","803Units",
                "FP","FixCt","Pool","LandValue","TotAcres","SaleQuarter","SaleYear", "Price"]]

useful_df.dropna(how='any',inplace=True)

useful_df.info()

X = useful_df[["CDU","Qual","TLA","GarCap","Bedrm","FND","801Units","802Units","803Units",
             "FP","FixCt","Pool","LandValue","TotAcres","SaleQuarter","SaleYear"]]
Y = useful_df["Price"]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34326 entries, 0 to 35102
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   CDU          34326 non-null  int64  
 1   Qual         34326 non-null  int64  
 2   TLA          34326 non-null  int64  
 3   GarCap       34326 non-null  int64  
 4   Bedrm        34326 non-null  float64
 5   FND          34326 non-null  float64
 6   801Units     34326 non-null  int64  
 7   802Units     34326 non-null  int64  
 8   803Units     34326 non-null  int64  
 9   FP           34326 non-null  int64  
 10  FixCt        34326 non-null  int64  
 11  Pool         34326 non-null  int64  
 12  LandValue    34326 non-null  int64  
 13  TotAcres     34326 non-null  float64
 14  SaleQuarter  34326 non-null  int64  
 15  SaleYear     34326 non-null  int64  
 16  Price        34326 non-null  float64
dtypes: float64(4), int64(13)
memory usage: 4.7 MB


C:\Users\Owner\anaconda3\lib\site-packages\pandas\util\_decorators.py:311: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)


In [200]:
#X = useful_df[[col for col in useful_df.columns if col != 'Price']]
#Y = useful_df["Price"]
# Y = np.reshape(list(Y),(-1,1))

x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.25)


print(tf.shape(x_train))
print(tf.shape(y_train))


#x_train_conv = np.expand_dims(x_train, axis=1)
#y_train_conv = np.expand_dims(y_train, axis=1)
#y_train_conv = np.expand_dims(y_train_conv, axis=1)
# for future convolutional network


#print(tf.shape(x_train_conv))
#print(tf.shape(y_train_conv))

tf.Tensor([25744    16], shape=(2,), dtype=int32)
tf.Tensor([25744], shape=(1,), dtype=int32)
tf.Tensor([25744     1    16], shape=(3,), dtype=int32)
tf.Tensor([25744     1     1], shape=(3,), dtype=int32)


In [203]:
metric = tfa.r_square.RSquare()

model = keras.Sequential([
    keras.layers.Dense(15, input_shape=[len(X.columns)], activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1, activation='linear')
    ])

model.compile(optimizer='adam',loss='mean_squared_error',metrics=[metric])

fit = model.fit(x_train,y_train,epochs=15)

Epoch 1/15
805/805 [==============================] - 1s 951us/step - loss: 15867242496.0000 - r_square: 0.0738
Epoch 2/15
805/805 [==============================] - 1s 911us/step - loss: 5872286720.0000 - r_square: 0.6572
Epoch 3/15
805/805 [==============================] - 1s 864us/step - loss: 5650439168.0000 - r_square: 0.6702
Epoch 4/15
805/805 [==============================] - 1s 900us/step - loss: 5356637696.0000 - r_square: 0.6873
Epoch 5/15
805/805 [==============================] - 1s 892us/step - loss: 5003694080.0000 - r_square: 0.7079
Epoch 6/15
805/805 [==============================] - 1s 939us/step - loss: 4651738624.0000 - r_square: 0.7285
Epoch 7/15
805/805 [==============================] - 1s 969us/step - loss: 4379338240.0000 - r_square: 0.7444
Epoch 8/15
805/805 [==============================] - 1s 920us/step - loss: 4214697728.0000 - r_square: 0.7540
Epoch 9/15
805/805 [==============================] - 1s 911us/step - loss: 4138270976.0000 - r_square: 0.7584


In [204]:
trained = model.predict(x_train)

model.evaluate(x_test, y_test)

269/269 [==============================] - 0s 806us/step - loss: 3904608256.0000 - r_square: 0.7598


[3904608256.0, 0.7598353624343872]